### ISSUE TITLE
Any version for Godot 4?

### ISSUE THREAD

**Issue by jospic** [francogarcia/GD-PDF#6]
Hi, this is a nice extension that I've been using for a while with Godot version 3.
Are you going to port to version 4?
Thanks in advance.
-j

**Comment by francogarcia** [comment]
Hello, @jospic,
How are you?

I have not tried Godot 4 yet, though, if there is interest, I probably can port it.

However, as I am finishing the implementation of a research project, I may only have time to work on this around August.

Best regards,
Franco

**Comment by jospic** [comment]
Hi Franco,
this is great! The new Godot extension system not requires recompiling the entire system and probably the porting will probably be easier for you too.
We'll update soon and good luck.  
Thank you.
-j

**Comment by francogarcia** [comment]
Hello, @jospic,
How are you?

I have created a pull request with an updated version in #7 .
From a quick test, it seems to be working with Godot's 4.0 branch.

Could you check whether it works for you?

Best regards,
Franco

**Comment by jospic** [comment]
Hello Franco,
your branch for version 4 works perfectly!
Naturally, when you have more free time, you can consider transforming it into an external module so as to avoid compiling the entire engine at each version change.
For now, thanks a lot!
-j

**Comment by francogarcia** [comment]
Hello, @jospic,
How are you?

Thanks for the link.
It is nice to see that GDNative became GDExtension, which is better supported now.
These did not exist when this module had been originally written.

I guess I can investigate it when I have free time, although this will have a low priority for now.

As this project has external dependencies, I believe I would need to generate dynamic libraries (DLL, SO, dylib, etc.) for all supported platforms.
Unfortunately, I can only compile them for some platforms (Linux, Windows, probably Android).
Perhaps macOS if OSXCross still works.

Although it certainly is less convenient and harder to use, the module has the benefit of letting people compile to all platforms they have access to.

Regardless, I will open an issue as a reminder to do it at some point.

Best regards,
Franco
