### ISSUE TITLE
Does this allow viewing pdf?

### ISSUE THREAD

**Issue by shafnaz** [francogarcia/GD-PDF#9]
Is there an internal pdf viewer?

**Comment by francogarcia** [comment]
Hello, @shafnaz,
How are you?

The module only creates simple PDF files.
It was written circa 2016 to generate reports for healthcare professionals in a therapeutic game.

If you need a viewer, I guess a quick hack would be to convert each page of a PDF file to a image (for instance, in the JPG or PNG formats), then open each image in your Godot project.
For instance, you could use an external tool such as [ImageMagick](https://imagemagick.org/) to generate the images by starting a process with ```OS.execute()``` ([documentation](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-execute)).

Best regards,
Franco
